fls-bioinformatics-core/galaxy-tools

trimmomatic/trimmomatic.xml

This is a fix to "planemo lint" which was failing due to a (No <when /> block found for select option 'no') warning.

added an empty when clause to satisfy planemo lint

---

tools/macs21/README.rst
tools/macs21/macs21_wrapper.xml

PR adds explicit support for paired-end input data in the MACS 2.1 tool, by exposing the `--format` option to the user and making them set the input format explicitly.
It is intended to address issue #10.

Add explicit support for paired end input in MACS 2.1

---

tools/trimmomatic/README.rst
tools/trimmomatic/install_tool_deps.sh
tools/trimmomatic/run_planemo_tests.sh
tools/trimmomatic/tool_dependencies.xml
tools/trimmomatic/trimmomatic.xml

PR to update the `trimmomatic` tool to install and run the latest version of Trimmomatic 0.36.

Update 'trimmomatic' tool to use Trimmomatic 0.36

---

.travis.yml

PR which fixes failures with the Travis-CI tests due to a problem with installing `planemo` - see https://github.com/galaxyproject/planemo/issues/520 for the background.

Fix Travis-CI failures when planemo fails to install

---

tools/ceas/data_manager/data_manager_ceas_fetch_annotations.py

This PR fixes the bug reported in issue #16, where the CEAS data manager is broken under Galaxy v16.04.

Remove dependency on galaxy.utils for JSON read/write in CEAS data manager

---

README.rst
local_dependency_installers/R.sh
local_dependency_installers/biopython.sh
local_dependency_installers/bx_python.sh
local_dependency_installers/ceas.sh
local_dependency_installers/macs2.sh
local_dependency_installers/numpy.sh
local_dependency_installers/pal_finder.sh
local_dependency_installers/pandaseq.sh
local_dependency_installers/perl.sh
local_dependency_installers/primer3_core.sh
local_dependency_installers/python_mysql.sh
local_dependency_installers/rnachipintegrator.sh
local_dependency_installers/trimmomatic.sh
local_dependency_installers/ucsc_tools.sh
local_dependency_installers/weeder.sh
local_dependency_installers/xlsxwriter.sh
tools/ceas/install_tool_deps.sh
tools/macs21/install_tool_deps.sh
tools/pal_finder/install_tool_deps.sh
tools/rnachipintegrator/install_tool_deps.sh
tools/trimmomatic/install_tool_deps.sh
tools/weeder2/install_tool_deps.sh

PR to move the script functionality which performs local installation of tool dependencies for testing into separate files, in order to facilitate allow reuse (e.g. for local installation of dependencies into a Galaxy instance).
The idea is that installer functions will be grouped into files in the `local_dependency_installers` directory, e.g.:
.../local_dependency_installers/trimmomatic.sh
The installer script will source the files that it needs and then invoke the appropriate functions, e.g.:
...
. $(dirname $0)/../../local_dependency_installers/trimmomatic.sh
...
install_trimmomatic_0_36 $LOCAL_TOOL_DEPS_DIR
...

Move local tool dependency installation functions into separate files

---

local_dependency_installers/ucsc_tools.sh
tools/macs21/README.rst
tools/macs21/install_tool_deps.sh
tools/macs21/macs21_wrapper.py
tools/macs21/macs21_wrapper.xml
tools/macs21/run_planemo_tests.sh
tools/macs21/tool_dependencies.xml

PR to fix two issues:
1. On some sytems the `bedgraphToBigWig` step fails because the input bedgraph file is incorrectly sorted; this fix inserts a `bedSort` step beforehand to ensure that the input is sorted correctly.
2. Explicitly checks the exit status of the `MACS2` command and forces stop if this is non-zero (previously the tool will continue to run).

Fix macs21 bigWig generation and termination on error

---

.travis.yml

The update to using the `conda` dependency resolver appears to have broken the Travis-CI tests for a couple of tools (specifically `pal_finder` and `macs21`).
The immediate solution is to turn off the use of `conda` when running the tests for now. Longer term however the tool dependencies should be migrated to `conda`.

Turn off conda auto-init and auto-install when running planemo tests

---

tools/pal_finder/README.rst
tools/pal_finder/pal_finder_wrapper.sh
tools/pal_finder/pal_finder_wrapper.xml

PR which deals with very big log files that can be produced from both `pal_finder` and `pal_filter` in some cases (for example, when an error occurs in the `pal_finder` Perl script, or when `pandaseq` warns of a large number of poor quality assemblies).
The update captures the log files and limits the number of lines that are reported to 500. The limit is imposed regardless of whether the job was successful or not.

Update pal_finder tool to handle big logfiles

---

tools/trimmomatic/trimmomatic.xml

Added missing minAdapterLength and keepBothReads parameters for palindrome mode of ILLUMINACLIP step.
(forked from @cgirardot and rebased).

Added missing minAdapterLength and keepBothReads parameters

---

.travis.yml

PR which updates the test environment used by Travis CI to:
* No longer install `samtools`
* Use a dedicated virtualenv to install `planemo` into
These changes should reduce the amount of work being done to set up the test environment in future.

Travis CI: update test environment (samtools/planemo/Galaxy source)

---

tools/motif_tools/package_motif_tools.sh

The `motif_tools` tools were broken on the toolshed because the packager script didn't include the Perl scripts; this PR should fix this problem.

motif_tools: add missing Perl scripts to packager script

---

tools/pal_finder/fastq_subset.py
tools/pal_finder/pal_finder_macros.xml
tools/pal_finder/pal_finder_wrapper.sh
tools/pal_finder/pal_finder_wrapper.xml
tools/pal_finder/test-data/illuminaPE_microsats_subset.out.re_match

PR aiming to address issue #51 and enable the tool to use a subset of read pairs from the input Fastq files.

pal_finder: use a subset of reads

---

tools/pal_finder/pal_finder_wrapper.sh
tools/pal_finder/pal_finder_wrapper.xml

PR to address issue #38, by trapping for cases where user requests zero number of N-mer repeat units but non-zero number of (N+1)-mer repeats (which crashes the tool).
Now the tool will stop with a sensible error message if this situation occurs.

Palfinder: trap for bad n mers specification

---

tools/pal_finder/README.rst
tools/pal_finder/fastq_subset.py
tools/pal_finder/pal_finder_wrapper.xml

The current implementation of `fastq_subset.py` (used for extracting a subset of reads from a pair of Fastq files before input to `pal_finder`) appears to be extremely slow, and for large Fastqs (of the order of 7Gb?) fails to complete before the time limit of 7 days imposed locally on cluster jobs.
This PR removes the current Fastq iteration code (based on `biopython`s `FastqGeneralIterator` class), and reimplements using a custom buffered approach which is (hopefully) more efficient.

pal_finder: update fastq_subset.py to improve efficiency

---

tools/rnachipintegrator/README.rst
tools/rnachipintegrator/rnachipintegrator_macros.xml

`RnaChipIntegrator` has been updated to version 1.1.0; this PR updates the Galaxy tools to use this version. NB although there are new options in `RnaChipIntegrator`, this PR doesn't add any new features to the tool.

rnachipintegrator: update to latest RnaChipIntegrator version 1.1.0.

---

tools/motif_tools/motif_tools_macros.xml

PR to address issue #70 by updating the `perl-bioperl` conda dependency of the `motif_tools` Galaxy tool package to version 1.7.2 (which seems to work okay).

motif_tools: bump perl-bioperl dependency from 1.6.924 to 1.7.2.

---

.travis.yml
tools/rnachipintegrator/data_manager/data_manager_rnachipintegrator_fetch_canonical_genes.xml
tools/rnachipintegrator/rnachipintegrator_canonical_genes.xml
tools/rnachipintegrator/rnachipintegrator_wrapper.xml

PR which attempts to fix the Travis CI builds where tests failed for all tools due to an error with planemo missing Xunit. This seemed to affect planemo version 0.57.1 testing against Galaxy release 17.05.
Updating to test against Galaxy 18.09 fixed all builds except for RnaChipIntegrator, where the data manager test was now failing. It seems that when testing against for earlier Galaxy versions the data manager tests were not run and there is some issue generally with the test mechanism in this case - so for now the workaround is to comment out the data manager test.

Fix errors with Travis CI builds (planemo missing Xunit?)

---

tools/trimmomatic/trimmomatic_macros.xml

I ran into an error using the trimmomatic docker image that is generated from the trimmomatic conda package.
These images are minimal busbox containers, and the readlink command there doesn't know about -e. -f is perfectly fine in this scenario:
```
Print value of a symbolic link or canonical file name
-f, --canonicalize            canonicalize by following every symlink in
every component of the given name recursively;
all but the last component must exist
-e, --canonicalize-existing   canonicalize by following every symlink in
every component of the given name recursively,
all components must exist
```

readlink -f instead of readlink -e more portable

---

tools/trimmomatic/README.rst
tools/trimmomatic/trimmomatic.xml
tools/trimmomatic/trimmomatic_macros.xml

PR which implements the suggestion appended to PR #74, to use the version of `readlink` from the `coreutils` package.
The previous PR switched from `-e` to `-f`, but this reportedly broke the tool for MacOS. This latest PR restores `-e` but using `coreutils` should ensure that this time it is supported across all platforms.

Trimmomatic: use 'readlink' from coreutils package for cross-platform support

---

.travis.yml

PR which fixes broken Travis CI testing by updating to Python 3.6 (also addressing issue #76).
The update also requires that the target Galaxy version that the tool tests are run against is bumped to 19.09 (this is the first version that supported Python 3).
In addition some other updates have been made, specifically:
* Drop installation of Java (this should be taken care of by the conda dependency resolver now)
* Drop update of `setuptools` in the virtualenv used to install `planemo` (no longer required)

Update Travis CI tests to Python 3 & Galaxy 19.09

---

tools/trimmomatic/package_trimmomatic.sh

Update the packager script for the Trimmomatic tool, to handle the new way of specifying the tool version from PR #85.

Trimmomatic tool: update packager script

---

tools/macs21/README.rst
tools/macs21/macs21_wrapper.xml

Updates the `macs21` tool to specify more recent versions (377) of the UCSC tools (`fetchChromSizes`, `bedSort`, `bedGraphToBigWig` and `bedClip`) as the previous versions (357) were failing in the tool tests.
Also updates the tool version to `2.1.2-galaxy1`.

macs21: update versions of UCSC tools in requirements
